
export const CAR_ASSET_SCHEMA = {
  id: '',
  name: '',
  spriteUrl: '',
  type: '',
  baseDim: [],
  tl: [],
  dim: [],
  cr: [],
  theta_0: 0,
  minTheta: 0,
  maxTheta: 0,
  phase: 0,
  radius: 0,
  handleAngle: 0,
  colorRemap: { enabled: false, sourceColor: '#FF001A', remapTolerance: 10 },
  drawCode: '',
  updateCode: '',
  start: [0, 0],
  end: [0, 0], 
  duration: 1000,
  speedDependent: false,
  behavior: '',
}